### ISSUE TITLE
feat: Get Flathub verification

### ISSUE THREAD

**Issue by first-storm** [flathub/io.github.Predidit.Kazumi#23]
https://docs.flathub.org/docs/for-app-authors/verification

Follow the instruction here. @Predidit

**Comment by Predidit** [comment]
@first-storm 

Thank you for your reminder. I have completed the verification. However, the app store still shows it as unverified, which might take some time. Also, version 1.4.5 has been delayed again. Should we submit a PR to refresh it?

**Comment by first-storm** [comment]
> @first-storm
> 
> Thank you for your reminder. I have completed the verification. However, the app store still shows it as unverified, which might take some time. Also, version 1.4.5 has been delayed again. Should we submit a PR to refresh it?

It needs time to get it published.
